{% set name = "structuretoolkit" %}
{% set version = "0.0.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/structuretoolkit-{{ version }}.tar.gz
  sha256: c06924d926a597b7c76c3704e1127a9003e0f021131a70c7bc2b2f0ab25d7cee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - ase
    - numpy
    - scipy
    - versioneer
    - toml
  run:
    - python >=3.7
    - ase >=3.20.1,<=3.23.0
    - numpy >=1.23.5,<=1.26.4
    - scipy >=1.9.3,<=1.13.1

test:
  imports:
    - structuretoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/structuretoolkit
  summary: structuretoolkit - to analyse, build and visualise atomistic structures.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - pmrv
    - srmnitc
    - pyiron-runner
    - jan-janssen
