{% set name = "structuretoolkit" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/structuretoolkit-{{ version }}.tar.gz
  sha256: cfe918d29fb11d1deb957a806e80028fb00fec5f2a06fd7e3016239a58b9f7cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aimsgb >=1.0.3
    - ase >=3.22.1
    - matplotlib-base >=3.7.2
    - numpy >=1.19.5  # for numba and pytorch compatibility
    - phonopy >=2.20.0
    - pymatgen >=2023.7.20
    - pyscal >=2.10.18
    - pyxtal >=0.5.9
    - scipy >=1.11.1
    - scikit-learn >=1.3.0
    - spglib >=2.0.2
    - sqsgenerator >=0.2

test:
  imports:
    - structuretoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/structuretoolkit
  summary: structuretoolkit - to analyse, build and visualise atomistic structures.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
