{% set name = "structuretoolkit" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/structuretoolkit-{{ version }}.tar.gz
  sha256: 8b49fc9651191957b081ce5b6b0a8d4eaebfd703fdd6e40118d6b002300be7ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aimsgb >=1.0.3
    - ase >=3.22.1
    - matplotlib-base >=3.7.2
    - numpy >=1.19.5  # for numba and pytorch compatibility
    - phonopy >=2.20.0
    - pymatgen >=2023.8.10
    - pyscal >=2.10.18
    - pyxtal >=0.6.0
    - scipy >=1.11.1
    - scikit-learn >=1.3.0
    - spglib >=2.0.2
    - sqsgenerator >=0.2

test:
  imports:
    - structuretoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/structuretoolkit
  summary: structuretoolkit - to analyse, build and visualise atomistic structures.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
