{% set name = "structuretoolkit" %}
{% set version = "0.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/structuretoolkit-{{ version }}.tar.gz
  sha256: 8b49fc9651191957b081ce5b6b0a8d4eaebfd703fdd6e40118d6b002300be7ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ase >=3.22.1
    - matplotlib-base >=3.7.2
    - numpy >=1.23.5
    - scipy >=1.11.2

test:
  imports:
    - structuretoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/structuretoolkit
  summary: structuretoolkit - to analyse, build and visualise atomistic structures.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - pmrv
    - srmnitc
    - pyiron-runner
    - jan-janssen
