{% set name = "structuretoolkit" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/structuretoolkit-{{ version }}.tar.gz
  sha256: 8ef52d1a04d62b2e0964cb8007c04e1b6f5c0d0bdac4c8db11ff70414f51054d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ase >=3.22.1
    - matplotlib-base >=3.8.1
    - numpy >=1.26.0
    - scipy >=1.11.3

test:
  imports:
    - structuretoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/structuretoolkit
  summary: structuretoolkit - to analyse, build and visualise atomistic structures.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - pmrv
    - srmnitc
    - pyiron-runner
    - jan-janssen
