{% set name = "structuretoolkit" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/structuretoolkit-{{ version }}.tar.gz
  sha256: 81edfed56b9723fb0796fc010cf23d1e41ad85b3b1ceaf9d3e441f622fd25cf1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aimsgb >=0.1.3
    - ase >=3.22.1
    - matplotlib-base >=3.7.1
    - numpy >=1.19.5  # for numba and pytorch compatibility
    - phonopy >=2.19.1
    - pymatgen >=2023.5.31
    - pyscal >=2.10.18
    - scipy >=1.10.1
    - scikit-learn >=1.2.2
    - spglib >=2.0.2
    - sqsgenerator >=0.2

test:
  imports:
    - structuretoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/structuretoolkit
  summary: structuretoolkit - to analyse, build and visualise atomistic structures.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
