{% set name = "structuretoolkit" %}
{% set version = "0.0.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/structuretoolkit-{{ version }}.tar.gz
  sha256: 0637aa47f3064f4fcfc7b4bf6b5220a93d23a5aa290f4c3e6bc4233b53fd7539

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - ase
    - numpy
    - scipy
    - versioneer
    - toml
    - setuptools
  run:
    - python >={{ python_min }}
    - ase >=3.20.1,<=3.24.0
    - numpy >=1.23.5,<=1.26.4
    - scipy >=1.9.3,<=1.15.1

test:
  imports:
    - structuretoolkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/structuretoolkit
  summary: structuretoolkit - to analyse, build and visualise atomistic structures.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - pmrv
    - srmnitc
    - pyiron-runner
    - jan-janssen
