{% set name = "structuretoolkit" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/structuretoolkit-{{ version }}.tar.gz
  sha256: 4c22e5637945f626a71c3840dbae1325efce0040f58835685363ef867e5c318d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - ase
    - matplotlib-base
    - numpy
    - scipy
  run:
    - python >=3.6
    - ase >=3.20.1,<=3.22.1
    - matplotlib-base ==3.8.2
    - numpy >=1.23.5,<=1.26.2
    - scipy >=1.9.3,<=1.11.4

test:
  imports:
    - structuretoolkit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/structuretoolkit
  summary: structuretoolkit - to analyse, build and visualise atomistic structures.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - pmrv
    - srmnitc
    - pyiron-runner
    - jan-janssen
