schema_version: 1

context:
  name: structuretoolkit
  version: "0.0.46"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/structuretoolkit-${{ version }}.tar.gz
  sha256: a1355a145cce1e61826764c29b097aa584ab775798ae4fca9ec358e250d913ae

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - ase
    - numpy
    - scipy
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - ase >=3.20.1,<=3.29.0
    - numpy >=1.23.5,<=2.5.3
    - scipy >=1.15.0,<=1.18.0

tests:
  - python:
      imports:
        - structuretoolkit
      python_version:
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: structuretoolkit - to analyse, build and visualise atomistic structures.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/structuretoolkit

extra:
  recipe-maintainers:
    - niklassiemer
    - pmrv
    - srmnitc
    - pyiron-runner
    - jan-janssen
