schema_version: 1

context:
  name: structuretoolkit
  version: 0.0.32

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/structuretoolkit-${{ version }}.tar.gz
  sha256: 7ed506e197f92af8a20c4eb4335614efe80e20001aa89c335770d27659527382

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - ase
    - numpy
    - scipy
    - versioneer
    - toml
    - setuptools
  run:
    - python >=${{ python_min }}
    - ase >=3.20.1,<=3.25.0
    - numpy >=1.23.5,<=1.26.4
    - scipy >=1.9.3,<=1.15.2

tests:
  - python:
      imports:
        - structuretoolkit
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: structuretoolkit - to analyse, build and visualise atomistic structures.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/structuretoolkit

extra:
  recipe-maintainers:
    - niklassiemer
    - pmrv
    - srmnitc
    - pyiron-runner
    - jan-janssen
